name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1          # Pour les appels API (NYT)
  cupertino_icons: ^1.0.6 # Icônes iOS
  flutter_map: ^6.1.0     # Pour la carte
  latlong2: ^0.9.1        # Requis par flutter_map
  provider: ^6.1.2        # Pour la gestion du thème
  url_launcher: ^6.3.0    # Pour ouvrir les liens (version plus récente)
  shared_preferences: ^2.2.3 # INDISPENSABLE pour sauvegarder la clé API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Ou plus récent si tu utilises un SDK récent

flutter:
  uses-material-design: true
  assets:
    - assets/ # Pour charger ton image nature.jpg etc.