name: flutter_app # Remplace si besoin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  geolocator: ^10.1.0 # Envisage ^11.0.0 ou ^12.0.0 si compatible
  intl: ^0.19.0
  permission_handler: ^11.0.1 # Envisage ^11.3.0 ou plus récent
  path_provider: ^2.1.1 # Gardé pour SQFlite

  # --- SQFlite ---
  sqflite: ^2.3.3
  path: ^1.9.0
  # --- Fin SQFlite ---

  # --- Firebase & Google ---
  firebase_core: ^3.2.0 # Envisage ^3.3.0 ou plus récent
  firebase_auth: ^5.1.1 # Envisage ^5.3.0 ou plus récent
  google_sign_in: ^6.2.1
  # --- Fin Firebase & Google ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Envisage ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/icon/ # Seulement si utilisé DANS l'app

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/Greenwatch_Logo.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  ios: true
  image_path_ios: "assets/icon/Greenwatch_Logo.jpeg"
  remove_alpha_ios: true